### ISSUE TITLE
Tamper Chrome won't start

### ISSUE THREAD

**Issue by AdrienLemaire** [sirdarckcat/sirdarckcat.github.io#2]
After installing both the extension and the app, I'm still unable to use Tamper Chrome, the debugger console tab showing "Requires a second component" error:
![2017-05-19_17-26-31](https://cloud.githubusercontent.com/assets/260983/26239567/883864c0-3cb8-11e7-8cea-1679d60c9340.png)
Tried restarting the browser twice, didn't help.

Using Google Chrome Version 58.0.3029.110 (64-bit) from Arch Linux.

**Comment by sirdarckcat** [comment]
Oh, wow, thanks for letting us know!

This is really strange, out of curiosity, which operating system do you use?

**Comment by AdrienLemaire** [comment]
```
$ uname -a                                                                                         [17:39:23]
Linux xps_9360 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux
$ cat /etc/os-release                                                                              [17:39:26]
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

$ pacman -Qs chrome                                                                                [17:39:29]
local/google-chrome 58.0.3029.110-1
    An attempt at creating a safer, faster, and more stable browser (Stable Channel)
```

Fyi I was using tamper chrome last year on arch linux.
Thank you for the fast support !

**Comment by sirdarckcat** [comment]
do you have iptables/pf setup?

The way TC works is by opening a local port, so if you have a firewall rule preventing connections from localhost to localhost, this could happen.

**Comment by AdrienLemaire** [comment]
No such rule in my iptables. Also, when opening the application from the chrome store page (useless because I cannot access the settings that are in the extension), I cannot see any related port being open. Or would that be scriptview ?

```
$ Starting Nmap 7.40 ( https://nmap.org ) at 2017-05-19 17:54 JST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00013s latency).
Other addresses for localhost (not scanned): ::1
rDNS record for 127.0.0.1: localhost.localdomain
Not shown: 997 closed ports
PORT     STATE SERVICE
443/tcp  open  https
3306/tcp open  mysql
7741/tcp open  scriptview
```

**Comment by sirdarckcat** [comment]
no, the port is 34013. can you click on the link `background page (Inactive)` under Tamper Chrome (application) and send over the contents of the console.log?

Thanks

**Comment by sirdarckcat** [comment]
This issue was moved to google/tamperchrome#20
