### ISSUE TITLE
Elgato fake auth, state not sent

### ISSUE THREAD

**Issue by Mikescops** [sirdarckcat/sirdarckcat.github.io#3]
Hello,

I was trying to use your solution to connect elgato key light and i stumbled upon an issue while connecting the app to google home.

It asks for a state, but when you set it, it of course doesn't match the one that was supposedly sent before.

![image](https://user-images.githubusercontent.com/4266283/139663457-6ad1e2cc-45da-4b84-bdc1-be1664888097.png)

How did you pass this?

Thanks in advance 👍

**Comment by Mikescops** [comment]
Update,

My bad, I was using another short url service than tinyurl and i guess that one was not passing the state to the underlying url.

Thanks for your work!

**Comment by sirdarckcat** [comment]
Yep, tinyurl is necessary :-)
